### ISSUE TITLE
Feature request: UnitframesImproved (Large Healthbars)

### ISSUE THREAD

**Issue by Cruzix** [obble/modui_classic#41]
An option to make the healthbar bigger would be amazing, similar to this:

https://imgur.com/7qzO9vE

**Comment by Xaero252** [comment]
I'm currently using WTF Classic for this; but I agree it would be nice not to need another addon to accomplish. I had it almost working but gave up and installed WTF so I could play. I had an issue getting the background for the PlayerName frame to go away.

**Comment by wesker3** [comment]
I personally, dont like it at all. Looks ugly. :(

**Comment by obble** [comment]
No plans to add this as it feels slightly outside the remit of the modui design (modernising and tidying up the default UI rather than morphing it into something else too much).

Hopefully another designer picks it up and adds cross-compatibility - if they do I can assist them in getting the two addons working together.

**Comment by Cruzix** [comment]
https://www.curseforge.com/wow/addons/unitframesimproved

Found out that this addon works with modUI however you gotta delete 1 file because otherwise status text will overlap. 
![image](https://user-images.githubusercontent.com/6162744/64182439-8a140800-ce68-11e9-9cc9-62455439722b.png)

![image](https://user-images.githubusercontent.com/6162744/64182662-dbbc9280-ce68-11e9-83a6-4d863179b055.png)

Would be nice to have the same texture as the image in the original post though, but im happy about this anyways.
