### ISSUE TITLE
Some things aren't showing properly until...

### ISSUE THREAD

**Issue by antisocial89** [obble/modui_classic#69]
So far my testing involves clearing all cache and installing ONLY modui. I've tried the latest stable version and a zip straight from GitHub, issue is present on both.

The issue is when I login, the UI is changed (it's not default), there's skills where the bags normally are etc., but, the color isn't dark, and my pet's combat bar is tucked behind the combat bar. To temporarily fix this, I can hit escape and go to interface, then close out the interface window, then everything gets painted black like it's supposed to be and the pet bar gets moved above the combat bar where it's supposed to be.

I would show more screenshots but this is all I could grab before the servers started having issues today. This is what it looks like BEFORE doing the interface window trick.

Any ideas?

![Screenshot_10](https://user-images.githubusercontent.com/17038716/64478157-a87c4b00-d169-11e9-821e-3773ab40c524.png)

**Comment by antisocial89** [comment]
Servers came back up just as I posted this, here's the "after the interface trick" pic:

![Screenshot_11](https://user-images.githubusercontent.com/17038716/64478181-19bbfe00-d16a-11e9-8c55-b273d88bf42b.png)

**Comment by Xaero252** [comment]
Confirming this behavior. Also interesting is that this corrects the colors. 

The "interface trick" works because MultiActionBar_Update(); is being called by InterFaceOptionsPanels.lua from the Blizzard FrameXML. This more or less confirms that the Blizzard frames either aren't ready when the theming code is run, or it isn't being run at all.  PLAYER_ENTERING_WORLD should be sufficient for this, though... not sure why its actually happening, need more off time to read through code and test. (Note I am not the maintainer of this addon)
