### ISSUE TITLE
Old modui-vanilla

### ISSUE THREAD

**Issue by WrobotProfiles** [obble/modui_classic#9]
Possible to incorperate a lot of what you did with the old modui (maybe include the ImprovedUnitFrames - addon which works nicely with yours !

Have the options like onebag, on/off
and all the awesome shit youdid. Especially the Raid Frames.

If it doesnt come out on release - is it possible to copy parts of the old modui (like raid frames nd such) into this new folder ? or no.

Amazing work man!!!

love to help, give ideas. been using this since day one, on every char/server

Andoido#0218

**Comment by obble** [comment]
Hey, plan is to mostly keep it the same with a few new options that can be toggled on or off - there's already the ability to turn the onebag on or off for example.

raidframes are on the roadmap - unfortunately the client that wow classic is based on uses a totally different code base than 1.12.1 servers like Nostalrius did, so no way to port those over, it needs to be rewritten from the ground up.

Probably a good thing because some of that old code is very creaky.
